package com.tasks.string;

public class Domains {
    public static void main(String[] args) {

        String s = "RETAIL/ERKC\n" +
                "RETAIL/Avtoplatezi_NEW\n" +
                "FUNCTIONAL/Prav_Dep\n" +
                "FINANCE_AND_RISK/CBDBO\n" +
                "CORP/Calypso\n" +
                "RETAIL/CashFlow\n" +
                "RETAIL/Business_Portal\n" +
                "RETAIL/DSA_SELF\n" +
                "CORP/Filenet_OPVK\n" +
                "IT/ESMRC\n" +
                "PROJECTS/ECM_DOCS_MANAGEMENT\n" +
                "RETAIL/FCCM_Operations_control_AML\n" +
                "RETAIL/FCCM\n" +
                "IT/FRAUD\n" +
                "IT/FRAUD_DBOUL\n" +
                "IT/FRAUD_TSRPB\n" +
                "IT/FMAAS\n" +
                "OPERATION/DSA_DD\n" +
                "FINANCE_AND_RISK/HUNTER\n" +
                "IT/Matching\n" +
                "CORP/MDM_NT\n" +
                "RETAIL/MDM\n" +
                "RETAIL/MIS\n" +
                "RETAIL/ODS\n" +
                "CORP/KKMB\n" +
                "OPERATION/MPC\n" +
                "FINANCE_AND_RISK/SAP_UVHD\n" +
                "ADMSTR/FIORI\n" +
                "FINANCE_AND_RISK/SAP_GRC_AccessControl\n" +
                "ADMSTR/EASUP\n" +
                "FINANCE_AND_RISK/SAP_LM\n" +
                "IT/SAP_Enable_Now\n" +
                "IT/IH_SAP_Success_Factors\n" +
                "FINANCE_AND_RISK/SAP_SRM\n" +
                "ADMSTR/ASUN\n" +
                "ADMSTR/ROR\n" +
                "FINANCE_AND_RISK/SAP_ROR_DB\n" +
                "FINANCE_AND_RISK/UVHDP\n" +
                "IT/ServiceManager\n" +
                "PROCESSING/SmartVista\n" +
                "TRANSACT_SM/Transact_Retail\n" +
                "FINANCE_AND_RISK/TransactSM_SME\n" +
                "PROCESSING/UPOS\n" +
                "PROCESSING/UPOS_2_0\n" +
                "PROCESSING/WAY4\n" +
                "PROCESSING/DataMart\n" +
                "IT/WebExtension\n" +
                "IT/ABED\n" +
                "IT/OSS\n" +
                "ESB/ESB_Adapter_Swift\n" +
                "FINANCE_AND_RISK/AMRLiRT\n" +
                "CORP/Analitica\n" +
                "FINANCE_AND_RISK/SUZ\n" +
                "RETAIL/BACKOFFICE\n" +
                "FINANCE_AND_RISK/APKKB\n" +
                "FINANCE_AND_RISK/RISK\n" +
                "CORP/MOKK\n" +
                "RETAIL/ADWH\n" +
                "FINANCE_AND_RISK/BankAssurance\n" +
                "FINANCE_AND_RISK/BankAssuranse_INV\n" +
                "FINANCE_AND_RISK/PRKD\n" +
                "OPERATION/BBMO\n" +
                "RETAIL/FP_BR\n" +
                "FINANCE_AND_RISK/BusinessPlan\n" +
                "IT/DI\n" +
                "FINANCE_AND_RISK/Filial_Sberbank\n" +
                "PROCESSING/VIPISKA\n" +
                "RETAIL/SBOL_SWIFT\n" +
                "CORP/Depozitariy\n" +
                "IT/DIVIDEND\n" +
                "FINANCE_AND_RISK/DIS\n" +
                "RETAIL/ESA\n" +
                "CORP/EKS\n" +
                "CORP/EPS\n" +
                "RETAIL/ERIB_BB2\n" +
                "CORP/MRM_KM\n" +
                "EFS/EFS_FCR\n" +
                "CORP/MRM_KM_MMB_MS\n" +
                "EFS/EFS_SberPay\n" +
                "EFS/EFS_Autopay\n" +
                "EFS/EFS_Avtoplatezhy\n" +
                "EFS/EFS_KC3\n" +
                "FINANCE_AND_RISK/BankAssurance_EFS\n" +
                "EFS_BFS/EMPLOYEE_PROFILE\n" +
                "EFS/EFS_DEPOSIT_SBOL\n" +
                "EFS/EFS_GOSUSLUGI\n" +
                "EFS/EFS_CK_MOBILE\n" +
                "EFS/EFS_PoAttorney\n" +
                "CORP/EFS_DOS\n" +
                "CORP/BPBP\n" +
                "EFS/ERK_CM2\n" +
                "EFS/EFS_Planner\n" +
                "EFS/EFS_TECHNOBREAKS\n" +
                "EFS/EFS_FILE_TRANSFER\n" +
                "EFS/EFS_Hypothec\n" +
                "EFS/EFS_REQUISITES_MOBILE\n" +
                "EFS/EFS_Dcard_Issue\n" +
                "EFS/EFS_DK_MOBILE\n" +
                "EFS/EFS_CK_SBOL\n" +
                "EFS/EFS_DK_SBOL\n" +
                "EFS/EFS_DK_WEB\n" +
                "EFS/EFS_KO\n" +
                "EFS/EFS_Compliance_KB\n" +
                "EFS/EFS_TRANSFERS\n" +
                "CORP/MRM_KM_MMB_VS\n" +
                "RETAIL/Karty_1\n" +
                "EFS/EFS_Tarifs_CC\n" +
                "EFS/EFS_CREDITS_FL\n" +
                "EFS/EFS_FASCIAL_BIOMETRY\n" +
                "CORP/ERM_KM\n" +
                "EFS/EFS_MRM_RB\n" +
                "CORP/MRM_COMPAS_RTP\n" +
                "COMPONENT/Identification\n" +
                "EFS/Online_Encashment\n" +
                "COMPONENT/KASSA_RB\n" +
                "EFS/EFS_UBA\n" +
                "EFS/EFS_Caretakers\n" +
                "EFS/EFS_SERVICES\n" +
                "EFS/EFS_RPU\n" +
                "RETAIL/PPRB_FP_Perevody\n" +
                "EFS/EFS_PIP_VIP\n" +
                "EFS/EFS_Payments1\n" +
                "EFS/EFS_OMNY\n" +
                "EFS/EFS_PSCU\n" +
                "EFS/EFS_IPOS\n" +
                "EFS/EFS_OFFLINE_POS1\n" +
                "EFS/EFS_SIMSale\n" +
                "EFS/EFS_DCBIA\n" +
                "EFS/EFS_IDENTIFICATION_UKO\n" +
                "EFS/EFS_PROFILE_FL\n" +
                "COMPONENT/Profile_Yul\n" +
                "CORP/WPCCUFS\n" +
                "EFS/UWP\n" +
                "EFS/EFS_RM_VSP\n" +
                "EFS/EFS_RM_Telemarketing\n" +
                "CORP/EFS_RBiDOS\n" +
                "EFS/EFS_SUBSCRIPTIONS_MOBILE\n" +
                "COMPONENT/Notice\n" +
                "EFS_BFS/BFSOSEO\n" +
                "EFS/EFS_UKO_Session_control\n" +
                "EFS/EFS_IDENTIFICATION_ESIA\n" +
                "COMPONENT/Knowledge_base\n" +
                "EFS/EFS_ZoVO_UKO\n" +
                "RETAIL/Messenger_900\n" +
                "ESB/ESB_AS_Zapros\n" +
                "IT/MEF\n" +
                "CORP/ICTB\n" +
                "CORP/IRD\n" +
                "ESBGW/GW_DB_DZO\n" +
                "CORP/INFOBANK\n" +
                "IT/IPS\n" +
                "RETAIL/IRBIS\n" +
                "FINANCE_AND_RISK/KAKB\n" +
                "CORP/KC\n" +
                "CORP/Atlant\n" +
                "CORP/MIS\n" +
                "CORP/Patriot\n" +
                "FINANCE_AND_RISK/SKK_Underwriting\n" +
                "RETAIL/KKAF\n" +
                "IT/COSMOS\n" +
                "RETAIL/COD\n" +
                "ESB/ESB_CF\n" +
                "ESB/ESB_MDM\n" +
                "ESB/ESB_OKS\n" +
                "ESB/ESB_OP\n" +
                "ESB/ESB_PS\n" +
                "ESB/ESB_MON\n" +
                "ESB/ESB_SRD\n" +
                "ESB/ESB_UB\n" +
                "ESB/ESB_FR\n" +
                "ESB/ESB_FS\n" +
                "RETAIL/LD\n" +
                "FINANCE_AND_RISK/USVIT\n" +
                "FINANCE_AND_RISK/AFS\n" +
                "RETAIL/MBK\n" +
                "FUNCTIONAL/NKPDB2\n" +
                "OPERATION/OAD\n" +
                "RETAIL/OD\n" +
                "IT/UMD_Ora\n" +
                "FINANCE_AND_RISK/OKR\n" +
                "FINANCE_AND_RISK/OKR_DB\n" +
                "FINANCE_AND_RISK/OKR_CORE\n" +
                "ESB/CEP_RTDM_Retail\n" +
                "RETAIL/Parus_FT\n" +
                "FINANCE_AND_RISK/APKKB_NT\n" +
                "IT/Profile_4D\n" +
                "RETAIL/CKR_LT_NLPHandlers\n" +
                "PROCESSING/EGPO\n" +
//                "DEFAULT_TESTPMM_DB\n" +
                "PPRB/PPRB_Accounting_Engine_Phase_2\n" +
                "FINANCE_AND_RISK/PRB\n" +
                "PPRB/PPRB_OnlineComplianceControl\n" +
                "PPRB/PPRB_Autotransact\n" +
                "PPRB/PPRB_AIS\n" +
                "PPRB/PPRB_App_Core\n" +
                "PPRB/PPRB_KPMP\n" +
                "PPRB/PPRB_BPS_Reference\n" +
                "PPRB/PPRB_BPS_Product\n" +
                "PPRB/PPRB_NSI\n" +
                "PPRB/PPRB_BDSP_Deposits\n" +
                "RETAIL/PPRB_WED_DB\n" +
                "CORP/VKB\n" +
                "RETAIL/GBK\n" +
                "PPRB/PPRB_DEPOSIT_UL\n" +
                "RETAIL/Dinamichesky_Prising\n" +
                "PPRB/PPRB_DOM\n" +
                "PPRB/PPRB_KM\n" +
                "PPRB/PPRB_EKPIT_GG\n" +
                "PPRB/PPRB_KM_CB\n" +
                "FINANCE_AND_RISK/Zalog\n" +
                "PPRB/PPRB_EMIS\n" +
                "RETAIL/PPRB_ZP\n" +
                "PPRB/PPRB_MASSPAY\n" +
                "PPRB/PPRB_IMD\n" +
                "PPRB/PPRB_IM\n" +
                "PROCESSING/CPS\n" +
                "PPRB/PPRB_Encashment\n" +
                "PPRB/PPRB_COLLECTIVEDECISION\n" +
                "OPERATION/Monitoring_Platezhey\n" +
                "RETAIL/PPRB_Kredit\n" +
                "PPRB/PPRB_KUL\n" +
                "RETAIL/Kurs_Valut\n" +
                "PPRB/PPRB_MBP\n" +
                "PPRB/UDDK_RB\n" +
                "PPRB/PPRB_KSH_MC\n" +
                "RETAIL/PPRB_EKPIT\n" +
                "PPRB/PPRB_RSPIT\n" +
                "PPRB/PPRB_FP_NES\n" +
                "PPRB/PPRB_OKS\n" +
                "IT/PPRB_PU_VSFL\n" +
                "PPRB/PPRB_PLAT\n" +
                "PPRB/PPRB_EKOPOST\n" +
                "PPRB/PPRB_PJ\n" +
                "PPRB/PPRB_Registry_API\n" +
                "PPRB/PPRB_Conversion\n" +
                "PPRB/PPRB_FSKK\n" +
                "PPRB/PPRB_SPR_ML\n" +
                "PROCESSING/PPRB_StopList\n" +
                "FINANCE_AND_RISK/BankAssurance_PPRB\n" +
                "PPRB/PPRB_Teh_Core\n" +
                "PPRB/PPRB_Acquiring\n" +
                "PPRB/PPRBTCP\n" +
                "FRONT_SYSTEM/TFiDO\n" +
                "PPRB/AUTH\n" +
                "PPRB/PPRB_FAILOVER\n" +
                "PPRB/PPRB_MetaData\n" +
                "PPRB/PPRB_AS_UVsK\n" +
                "PPRB/PPRB_UKL\n" +
                "PPRB/PPRB_UDkSiD\n" +
                "PPRB/PPRB_UOD\n" +
                "PPRB/PPRB_RM\n" +
                "PPRB/PPRB_RC_UFS\n" +
                "PPRB/PPRB_Loyalty\n" +
                "PPRB/PPRB_RESERVES_LOANS4b\n" +
                "RETAIL/PPRB_Reserves\n" +
                "IT/PPRB_Digital\n" +
                "PPRB/PPRB_ELGO\n" +
                "RETAIL/PL_SBOL\n" +
                "RETAIL/Prometey\n" +
                "FINANCE_AND_RISK/Score\n" +
                "RETAIL/SberAPI\n" +
                "RETAIL/Sberbank_Automation_Business\n" +
                "ITECO_TEST/EMFT_5_SBK\n" +
                "FINANCE_AND_RISK/SborDannyh\n" +
                "RETAIL/Sverka\n" +
                "RETAIL/Sirius_FT\n" +
                "IT/SPKK\n" +
                "RETAIL/SITCENTER\n" +
                "FRONT_SYSTEM/SCAD\n" +
                "RETAIL/SMSB\n" +
                "RETAIL/SMSB_2\n" +
                "IT/SNUiL\n" +
                "IT/SNUILCD\n" +
                "PROCESSING/SM_POS_term\n" +
                "RETAIL/SPOOBK2\n" +
                "PROCESSING/StopList\n" +
                "IT/SUDIR\n" +
                "FINANCE_AND_RISK/SUCCR\n" +
                "PROCESSING/ATM_Scenarious\n" +
                "CORP/SEODO\n" +
                "CORP/DIF_TARIF\n" +
                "IT/Telecom\n" +
                "ESB/ESB_TFS\n" +
                "FINANCE_AND_RISK/UVZ\n" +
                "IT/CB\n" +
                "RETAIL/HABBL\n" +
                "FINANCE_AND_RISK/USV\n" +
                "FINANCE_AND_RISK/FS_FOP\n" +
                "CORP/FKD\n" +
                "FINANCE_AND_RISK/FOK\n" +
                "FINANCE_AND_RISK/Kalita\n" +
                "FINANCE_AND_RISK/VDMMZ\n" +
                "RETAIL/CAS_NSI\n" +
                "OPERATION/CARS\n" +
                "ESB/GW_CIB\n" +
                "ESB/ESB_GW_Email\n" +
                "OPERATION/EDO_GO\n" +
                "RETAIL/YUPITER_PAYMENTS\n" +
                "RETAIL/YUPITER_ZD\n" +
                "RETAIL/YUPITER_EMIR";

        String [] arr = s.split("\n");

        for (int i = 0; i < arr.length; i++) {
            String domen = arr[i].split("/")[0];
            String project = arr[i].split("/")[1];

            String printStr = domen + "_" + project + "(" + i + ", " + "\"" + domen + "\"" + ", "
                    + "\"" + project + "\"" + ", " + "\"" + domen + project + "\"" + ")" +  ",\n";
            System.out.println(printStr);

//                    String task =  "URL (или версия) ALM: hpalm.delta.sbrf.ru:81/qcbin/rest/domains/" + domen + "/projects/" + project + "\n" +
//                    "Domain в ALM: " + domen + "\n" +
//                    "Project в ALM: " + project + "\n" +
//                    "Логин: " + "bychkov-vd" + "\n" +
//                    "e-mail: " + "Bychkov.V.D@omega.sbrf.ru" + "\n" +
//                    "Описание: " + "По заданию от руководителя и пишу интеграцию c ALM в рамках проекта RQM для различных доменов и областей" + "\n" +
//                    "Ваша роль в проекте: " + "разработчик";
//                    System.out.println(task);
//
//            System.out.println("\n\n");
        }
    }
}
